kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-pvc-resize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  storageClassName: sfsturbo-sc
