apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-obs-static
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: obs.csi.huaweicloud.com
    # set your custom parallel FS bucket
    volumeHandle: custom-bucket
